### ISSUE TITLE
Attempting to install SVT 1.42 from CKAN fails

### ISSUE THREAD

**Issue by Code-Grump** [Galileo88/Stock-Visual-Terrain#1]
Trying to add SVT to my **1.1.3** install of KSP using CKAN selects version **1.42** as the compatible version.

When trying to download the SVT package, the following error is presented by CKAN:

> Failed to download "https://github.com/Galileo88/Stock-Visual-Terrain/releases/download/1.42/SVT.1.42.zip" - error: The request was aborted: The connection was closed unexpectedly.

Checking that URL, GitHub returns a 404. I also notice that there doesn't seem to be a version 1.42 in the "Releases" tab.

**Comment by tmbomber383** [comment]
For whatever reason, the link provided in CKAN sends you here:
https://github.com/Galileo88/Stock-Visual-Terrain
but the download link there doesn't actually have the subdirectory you're suppose to drop into gamedata.

Go to this link:
https://github.com/Galileo88/Stock-Visual-Terrain/releases/tag/2.0.2

That page has a download link for 2.0.2 that has the SVT subdirectory that's supposed to be put in your gamedata folder.

(don't forget to delete the old SVTKopernicus folder first)

**Comment by Code-Grump** [comment]
Is **SVT 1.42** not the correct version for **KSP 1.1.3**?

**Comment by tmbomber383** [comment]
Looking at the releases page, 1.5, 2.0, 2.0.1, & 2.0.2 are available for download.
I don't even see 1.42.

I'm running KSP AVC as well as CKAN. CKAN failed to update and AVC told me 2.0.2 was the new version, but gave me the incorrect download link. I went looking and found the revisions page with the working 2.0.2 link and manually updated it.

Edit... 
sorry, I just noticed your running KSP 1.1.3, I'm running 1.2.2, so I'm unsure what rev of SVT would go with 1.1.3.

Thinking....

I notice KSP 1.1.3 was released on June 21, 2016, and 1.2 was released in October 11, 2016.
SVT 1.5 was released on October 21, 2016. Is there a version of SVT between 1.42 & 1.5?

**Comment by Galileo88** [comment]
I have removed older versions of SVT and no longer support 1.1.3. this is why ckan cannot download SVT for you

**Comment by Code-Grump** [comment]
Removing the older version breaks the model used by ckan which assumes a publicly published version doesn't change and will **always** be available. Does it cause a problem to continue to host older, deprecated versions? Restoring the old version would be the simplest solution.
