### ISSUE TITLE
2.0.3 failing in CKAN

### ISSUE THREAD

**Issue by mavericknoob** [Galileo88/Stock-Visual-Terrain#3]
https://github.com/Galileo88/Stock-Visual-Terrain/releases says 2.0.2 is latest release, but ckan keeps trying to pull 2.0.3 which is noted on release page but not marked latest. Not sure what you have in mind, but whatever you did broke ckan. BTW, I'm not having connection issues with any other mods
![ckan](https://cloud.githubusercontent.com/assets/20135196/24075385/8e1a5da6-0bd7-11e7-9326-c7c5f85d7905.jpg)

**Comment by Darael** [comment]
2.0.3 is no longer noted on the release page, and (having just tested) CKAN pulls 2.0.2 now.  This can probably be closed.
